### ISSUE TITLE
Error trying to compile bitstard

### ISSUE THREAD

**Issue by githare** [bitstar/bitstar#3]
Hi
I'm trying to compile bitstard (not the QT version!) on a raspberry pi 2, and I get this:

$ make -f makefile.unix

/bin/sh ../share/genbuild.sh obj/build.h
g++ -c -O2 -pthread -Wall -Wextra -Wformat -Wformat-security -Wno-unused-parameter -g -DBOOST_SPIRIT_THREADSAFE -I/home/xxxx/bitstar/src -I/home/xxxx/bitstar/src/obj -DUSE_UPNP=0 -DUSE_IPV6=1 -DHAVE_BUILD_INFO -fno-stack-protector -fstack-protector-all -Wstack-protector -D_FORTIFY_SOURCE=2  -MMD -MF obj/scrypt_mine.d -o obj/scrypt_mine.o scrypt_mine.cpp
scrypt_mine.cpp:32:23: fatal error: xmmintrin.h: No such file or directory
 #include <xmmintrin.h>
                       ^
compilation terminated.
makefile.unix:160: recipe for target 'obj/scrypt_mine.o' failed
make: **\* [obj/scrypt_mine.o] Error 1

**Comment by bitstar** [comment]
Sorry for the late reply, but Bitstar source isn't ARM compatible.
